name: Uptycs Vulnerability Scanner
description: Scans containers for known vulnerabilities
author: Uptycs
inputs:
  #############################################################################
  # Required Inputs
  #############################################################################
  uptycs-secret:
    description: Tenant-specific secret for authenticating to uptycs
    required: true
  image-id:
    description: ID of the docker image to scan for vulnerabilities
    required: true
  hostname:
    description: The hostname of the uptycs stack to send results to
    required: true
  #############################################################################
  # Optional inputs
  #############################################################################
  fatal-cvss-score:
    description: The CVSS score at which a detected vulnerability should fail the build
    required: false
    default: '8'
  custom_ca_cert:
    description: The path to a custom CA Cert to use for connecting to uptycs.
    required: false
    default: ''
  vulnerabilities_enabled:
    description: Enable or disable vulnerability scanning.
    required: false
    default: true
  secret_scanning_enabled:
    description: Enable or disable secret scanning.
    required: false
    default: true
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        env | grep 'GITHUB' > .uptycs_env
        
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume $(pwd)/uptycs-ci/scripts/docker-image-scan:/usr/local/bin/docker-image-scan \
          --volume $(pwd)/uptycs-ci/scripts/secret_paths_to_query.py:/usr/local/bin/secret_paths_to_query.py \
          --volume $(pwd)/uptycs-ci/scripts/hax.sh:/usr/local/bin/hax.sh \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          --entrypoint /usr/local/bin/hax.sh \
          uptycs/uptycs-ci:5.5.1.2-Uptycs-202211171427 \
          --with-vulnerabilities \
          --with-secrets \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}" \
          --secret-path '/etc/%%'
      if: ${{ inputs.custom_ca_cert == '' }}
    - shell: bash
      run: |
        env | grep 'GITHUB' > .uptycs_env

        docker run --rm --volume $(pwd):/mnt alpine:bash cp
        
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          --volume $(pwd)/uptycs-ci/scripts:/usr/local/bin \
          --volume "${{ inputs.custom_ca_cert }}:${{ inputs.custom_ca_cert }}" \
          uptycs/uptycs-ci:5.5.1.2-Uptycs-202211171427 \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}"
      if: ${{ inputs.custom_ca_cert != '' }}
