name: Uptycs Vulnerability Scanner
description: Scans containers for known vulnerabilities
author: Uptycs
inputs:
  #############################################################################
  # Required Inputs
  #############################################################################
  uptycs-secret:
    description: Tenant-specific secret for authenticating to uptycs
    required: true
  image-id:
    description: ID of the docker image to scan for vulnerabilities
    required: true
  hostname:
    description: The hostname of the uptycs stack to send results to
    required: true
  #############################################################################
  # Optional inputs
  #############################################################################
  fatal-cvss-score:
    description: The CVSS score at which a detected vulnerability should fail the build
    required: false
    default: '8'
  custom-ca-cert:
    description: The path to a custom CA Cert to use for connecting to uptycs.
    required: false
    default: ''
  vulnerabilities-enabled:
    description: Enable or disable vulnerability scanning.
    required: false
    default: true
  secret-scanning-enabled:
    description: Enable or disable secret scanning.
    required: false
    default: true
  secret-path:
    description: Path to scan for secrets.
    required: false
    default: "/%%"
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        env | grep 'GITHUB' > .uptycs_env
    - shell: bash
      # Note: See https://github.com/actions/runner/issues/1483 for details on
      # the syntax for this boolean logic.
      if: ${{ (inputs['vulnerabilities-enabled'] == 'true' && true || false) && (inputs['secret-scanning-enabled'] == 'true' && true || false) }}
      run: |
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          uptqa007/uptycs-ci:5.7.0.18 \
          --with-vulnerabilities \
          --with-secrets \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}" \
          --secret-path "${{ inputs.secret-path }}"
    - shell: bash
      # Note: See https://github.com/actions/runner/issues/1483 for details on
      # the syntax for this boolean logic.
      if: ${{ (inputs['vulnerabilities-enabled'] == 'true' && true || false) && (inputs['secret-scanning-enabled'] == 'false' && true || false) }}
      run: |
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          uptqa007/uptycs-ci:5.7.0.18 \
          --with-vulnerabilities \
          --no-secrets \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}"
    - shell: bash
      # Note: See https://github.com/actions/runner/issues/1483 for details on
      # the syntax for this boolean logic.
      if: ${{ (inputs['vulnerabilities-enabled'] == 'false' && true || false) && (inputs['secret-scanning-enabled'] == 'true' && true || false) }}
      run: |
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          uptqa007/uptycs-ci:5.7.0.18 \
          --no-vulnerabilities \
          --with-secrets \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}" \
          --secret-path "${{ inputs.secret-path }}"
    - shell: bash
      run: |
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          --volume $(pwd)/uptycs-ci/scripts:/usr/local/bin \
          --volume "${{ inputs.custom-ca-cert }}:${{ inputs.custom-ca-cert }}" \
          uptqa007/uptycs-ci:5.7.0.18 \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}"
      if: ${{ inputs.custom-ca-cert != '' }}
