name: Uptycs Vulnerability Scanner
description: Scans containers for known vulnerabilities
author: Uptycs
inputs:
  #############################################################################
  # Required Inputs
  #############################################################################
  uptycs-secret:
    description: Tenant-specific secret for authenticating to uptycs
    required: true
  osquery-flags:
    description: Flags file to be used by osquery
    required: true
  image-id:
    description: ID of the docker image to scan for vulnerabilities
    required: true
  #############################################################################
  # Optional inputs
  #############################################################################
  fatal-cvss-score:
    description: The CVSS score at which a detected vulnerability should fail the build
    required: false
    default: '8'
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: mkdir -p .uptycs_env && env | grep 'GITHUB_\|ACTIONS_\|RUNNER_\|INPUT_\|CI' > .uptycs_env/github
    - shell: bash
      run: |
        cat .uptycs_env/github
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env/github \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          uptycs/uptycs-ci:5.3.0.11-Uptycs-202208291926-x86_64-2-delete-2 \
          --ci-runner-type github \
          --verbose \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --osquery-flags "${{ inputs.osquery-flags }}"
        cat $GITHUB_STEP_SUMMARY
