name: Uptycs Vulnerability Scanner
description: Scans containers for known vulnerabilities
author: Uptycs
inputs:
  #############################################################################
  # Required Inputs
  #############################################################################
  uptycs-secret:
    description: Tenant-specific secret for authenticating to uptycs
    required: true
  image-id:
    description: ID of the docker image to scan for vulnerabilities
    required: true
  hostname:
    description: The hostname of the uptycs stack to send results to
    required: true
  #############################################################################
  # Optional inputs
  #############################################################################
  fatal-cvss-score:
    description: The CVSS score at which a detected vulnerability should fail the build
    required: false
    default: '8'
  custom-ca-cert:
    description: The path to a custom CA Cert to use for connecting to uptycs.
    required: false
    default: ''
  vulnerabilities-enabled:
    description: Enable or disable vulnerability scanning.
    required: false
    default: true
  secret-scanning-enabled:
    description: Enable or disable secret scanning.
    required: false
    default: true
  secret-paths:
    description: Paths to scan for secrets.
    required: false
    default: "/%%"
runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        env | grep 'GITHUB' > .uptycs_env
    - shell: bash
      if: ${{ (inputs.vulnerabilities-enabled == 'true' && 'true' || 'false') && (inputs.secret-scanning-enabled == 'true' && 'true' || 'false') }}
      # if: ${{ inputs.vulnerabilities-enabled && inputs.secret-scanning-enabled }}
      run: |
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume $(pwd)/uptycs-ci/scripts/docker-image-scan:/usr/local/bin/docker-image-scan \
          --volume $(pwd)/uptycs-ci/scripts/secret_paths_to_query.py:/usr/local/bin/secret_paths_to_query.py \
          --volume $(pwd)/uptycs-ci/scripts/hax.sh:/usr/local/bin/hax.sh \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          --entrypoint /usr/local/bin/hax.sh \
          uptycs/uptycs-ci:5.5.1.12-Uptycs-202212161612 \
          --with-vulnerabilities \
          --with-secrets \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}" \
          --secret-path "${{ inputs.secret-paths }}"
    - shell: bash
      if: ${{ (inputs.vulnerabilities-enabled == 'true' && 'true' || 'false') && (inputs.secret-scanning-enabled == 'false' && 'false' || 'true') }}
      # if: ${{ inputs.vulnerabilities-enabled && inputs.secret-scanning-enabled }}
      run: |
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume $(pwd)/uptycs-ci/scripts/docker-image-scan:/usr/local/bin/docker-image-scan \
          --volume $(pwd)/uptycs-ci/scripts/secret_paths_to_query.py:/usr/local/bin/secret_paths_to_query.py \
          --volume $(pwd)/uptycs-ci/scripts/hax.sh:/usr/local/bin/hax.sh \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          --entrypoint /usr/local/bin/hax.sh \
          uptycs/uptycs-ci:5.5.1.12-Uptycs-202212161612 \
          --with-vulnerabilities \
          --no-secrets \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}"
    - shell: bash
      if: ${{ (inputs.vulnerabilities-enabled == 'false' && 'false' || 'true') && (inputs.secret-scanning-enabled == 'true' && 'true' || 'false') }}
      # if: ${{ inputs.vulnerabilities-enabled && inputs.secret-scanning-enabled }}
      run: |
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume $(pwd)/uptycs-ci/scripts/docker-image-scan:/usr/local/bin/docker-image-scan \
          --volume $(pwd)/uptycs-ci/scripts/secret_paths_to_query.py:/usr/local/bin/secret_paths_to_query.py \
          --volume $(pwd)/uptycs-ci/scripts/hax.sh:/usr/local/bin/hax.sh \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          --entrypoint /usr/local/bin/hax.sh \
          uptycs/uptycs-ci:5.5.1.12-Uptycs-202212161612 \
          --no-vulnerabilities \
          --with-secrets \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}" \
          --secret-path "${{ inputs.secret-paths }}"
    - shell: bash
      run: |
        docker run --rm --privileged \
          --pid host \
          --net host \
          --restart no \
          --env-file .uptycs_env \
          --volume /var/run/docker.sock:/var/run/docker.sock:ro \
          --volume /var/run/docker.pid:/var/run/docker.pid:ro \
          --volume "$GITHUB_STEP_SUMMARY:$GITHUB_STEP_SUMMARY" \
          --volume $(pwd)/uptycs-ci/scripts:/usr/local/bin \
          --volume "${{ inputs.custom-ca-cert }}:${{ inputs.custom-ca-cert }}" \
          uptycs/uptycs-ci:5.5.1.12-Uptycs-202212161612 \
          --image-id "${{ inputs.image-id }}" \
          --uptycs-secret "${{ inputs.uptycs-secret }}" \
          --ci-runner-type github \
          --fatal-cvss-score "${{ inputs.fatal-cvss-score }}" \
          --uptycs-hostname "${{ inputs.hostname }}"
      if: ${{ inputs.custom-ca-cert != '' }}
