---
name: build
"on":
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Build an Image
        id: image_build
        run: |
          docker build -t my-organization/my-app:${{ github.sha }} \
            --iidfile=image_id.out .
          echo ::set-output name=image_id::$(cat image_id.out)

      - name: Run Uptycs Vulnerability Scanner
        uses: uptycslabs/uptycs-action@3.7.4
        with:
          uptycs-secret: ${{ secrets.UPTYCS_SECRET }}
          hostname: ${{ secrets.UPTYCS_HOSTNAME }}
          image-id: ${{ steps.image_build.outputs.image_id }}
          install_dir: "/tmp/uptycs-test"
      - name: Publish Scanned Image
        run: |
          docker push my-organization/my-app:${{ github.sha }}
